name: Selenium Regression Suite

# Run the pipeline on every push to teh main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #1. pull the code from github to runner
      - name: Checkout code
        uses: actions/checkout@v4

      #2. Setup Java environment (JDK21)
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      #3. Setup Chrome
      # GitHub Hosted Runners already have Chrome installed.
      # This step just verifies the version to ensure it's ready.
      - name: Check Browser Version
        run: google-chrome --version

      #4. Run Cucumber Tests
      - name: Run Cucumber Tests
        #run: mvn clean test -Dtest=Runner.TestRunner -Dbrowser=headless -PRegression
        #run: mvn clean verify -Dtest=Runner.TestRunner -Dbrowser=headless -PRegression
        # Adding -Dmaven.test.failure.ignore=true ensures the report is always generated
        run: mvn clean verify -Dtest=Runner.TestRunner -Dbrowser=headless -PRegression -Dmaven.test.failure.ignore=true

      # 5. Run Reruns (Only if failed.txt is not empty)
      - name: Run Failed Tests Rerun
        if: always()
        # This only runs if failed.txt exists and has content
        run: |
          if [ -s target/failed.txt ]; then
            mvn test -Dtest=FailedTestRunner -Dbrowser=headless
          else
            echo "No failed tests to rerun."
          Fi

      # 6. Upload Artifacts
      - name: Upload Cucumber Test Reports
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-test-reports
          path: target/cucumber-visual-report/
          retention-days: 5
      
